### ISSUE TITLE
Add an option to keep original text hidden while translating

### ISSUE THREAD

**Issue by MRGRD56** [MRGRD56/textractor-translator#9]
As for now it can be done with this custom CSS

```css
.sentence:has(.sentence-translated.sentence-loading) > .sentence-original {
    visibility: hidden; /* or `display: none;` */
}
```
